# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a58f4af4c5c6760028a571d763e025380909e0c9431d075b289b0209a1c903323cd8eaf882f1605dbd68648d25c13fb2d8f408f319abf4fe80651e0f7e80b138

test:
  secret_key_base: c5f49a4180334125ba595ba7807f67de1dde175f386d4e1bce848359a980597450cb05206c5d73dbec5a03a0a31884befec7c048c4900632f96ce56ea5066091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2c16754ed97adb6c743785e9fba2095e6e3988177ac9768d1331ea784805e84618a717994219370576e7b61de6a78c34da7f21705be6195e5eefc1e65a2288c4
